# usa imagen node (Ultima version)
# Si requiere version especifica usar node:12
FROM node

#Establese el directorio de trabajo
WORKDIR /usr/src/app

#Copia el package.json y package-lock.json
COPY package*.json ./

#Instala las dependencias
RUN npm install

#Copia el resto de los archivos
COPY . .

#Expone el puerto 3000
EXPOSE 3000

#Ejecuta el comando npm start
CMD ["npm", "start"]
